version: '3.8'

x-app:
services:
  web:
    ports: ["8080:80"]
    image: morris:latest
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        USER_ID: ${USER_ID:-10000}
        GROUP_ID: ${GROUP_ID:-10000}
    environment:
      EDITOR: vi
      HISTFILE: /log/.bash_history # TODO: test
    labels:
      - "traefik.http.routers.morris.rule=Host(`morris.127.0.0.1.nip.io`)"
      #- "traefik.http.routers.morris.tls=true"
      - "traefik.enable=true"

  # not working
  dev:
    #image: morris:dev
    image: jekyll/jekyll
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
      - "35729:35729"
    expose: ["4000"]
    # build:
    #   target: base
    #   context: .
    #   dockerfile: docker/app/Dockerfile
    #   args:
    #     USER_ID: ${USER_ID:-10000}
    #     GROUP_ID: ${GROUP_ID:-10000}
    environment:
      EDITOR: vi
      HISTFILE: /log/.bash_history # TODO: test
    labels:
      - "traefik.http.routers.morris.rule=Host(`morris.127.0.0.1.nip.io`)"
      #- "traefik.http.routers.morris.tls=true"
      - "traefik.enable=true"
    volumes:
      #- .:/app:cached
      - './:/srv/jekyll'
      #- bundle:/bundle

networks:
  default:
    name: traefik
    external: true
